In [2]:
import pandas as pd

In [16]:
store_locs = pd.read_csv("../data/Retail_Food_Stores.csv")

store_locs = store_locs.loc[store_locs['County'].isin(['Queens', 'Kings', 'Bronx', 'New York', 'Richmond'])]

In [27]:
# subset to get only groceries

,County,License Number,Operation Type,Establishment Type,Entity Name,DBA Name,Street Number,Street Name,Address Line 2,Address Line 3,City,State,Zip Code,Square Footage,Georeference
1,Queens,756125,Store,JAC,7-ELEVEN INC,7-ELEVEN STORE #35026H,253-02,UNION TPKE.,NaN,NaN,GLEN OAKS,NY,11004,0,POINT (-73.71744 40.74408)
3,Richmond,756121,Store,JAC,LA ROCA FUERTE DELI & GROCERY COR,LA ROCA FUERTE DELI & G,570,MIDLAND AVE,NaN,NaN,STATEN ISLAND,NY,10306,0,POINT (-74.09327 40.5724)
4,Queens,756120,Store,JAC,JACKSONS DELI INC,MILLIE'S DELI,13-01,JACKSON AVE,NaN,NaN,LONG ISLAND CITY,NY,11101,0,POINT (-73.94959 40.74412)
5,Queens,756118,Store,JAC,PRODUCTOS MEXICANOS LA GUAD LLC,PRODUCTOS MEX LA GUDALU,92-24,CORONA AVE,NaN,NaN,ELMHURST,NY,11373,1100,POINT (-73.87145 40.74241)
8,New York,756114,Store,JAC,NY A&M 1990 CORP,NY A&M 1990,1187,1ST AVE,NaN,NaN,NEW YORK,NY,10065,0,POINT (-73.95954 40.76297)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21993,Bronx,600103,Store,JAC,SILJKOVIC RABA&VEZIRA,SCALINADA MEAT GROC&DEL,667,E 187TH ST,NaN,NaN,BRONX,NY,10458,800,POINT (-73.88565 40.85461)
21994,Bronx,600057,Store,JABCHK,S&S CHEESECAKE INC,S&S CHEESECAKE,222,W 238TH ST,NaN,NaN,BRONX,NY,10463,4000,POINT (-73.8997 40.88481)
21995,Bronx,600049,Store,JAC,NANIN FOOD CORP,C TOWN,2733,3RD AVE,NaN,NaN,BRONX,NY,10451,10000,POINT (-73.9211 40.81425)
21996,Bronx,600005,Store,JABCHK,ADDEO BAKERS INC,ADDEO BAKERS,2372,HUGHES AVE,NaN,NaN,BRONX,NY,10458,4000,POINT (-73.88745 40.85451)
23050,Queens,475040,Store,JADX,BAY SHORE BEER INC,BEVERAGE BARN,5TH,AVE&GARFIELD ST,NaN,NaN,BAY SHORE,NY,11706,0,POINT (-73.25875 40.72517)

In [20]:
# read in the healthy food flags
data = pd.read_csv("../data/Recognized_Shop_Healthy_Stores.csv")
data

,Store Name,Street Address,Address,Borough,Zip \nCode,Year Awarded,Program \nWave,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,SIRAH 1720 LLC,535 MARCY AVE,NaN,Brooklyn,11206,2020,8,40.696961,-73.949512,3.0,36.0,257.0,3338591.0,3.017390e+09,Bedford
1,FIRST STOP GROCERY INC,643 MARCY AVE,NaN,Brooklyn,11206,2020,8,40.692552,-73.948632,3.0,36.0,261.0,3049316.0,3.017710e+09,Bedford
2,AANDE DIRECT LLC,40 LEWIS AVE,NaN,Brooklyn,11206,2020,8,40.696576,-73.937777,3.0,36.0,283.0,3042883.0,3.015850e+09,Stuyvesant Heights
3,CENTRAL ORGANIC,67 CENTRAL AVE,NaN,Brooklyn,11206,2020,8,40.701096,-73.930445,4.0,34.0,425.0,3072058.0,3.031640e+09,Bushwick South
4,194 THROOP FOOD CORP,777 PARK AVE,NaN,Brooklyn,11206,2020,8,40.698191,-73.944311,3.0,36.0,257.0,3335580.0,3.017320e+09,Bedford
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,El Barrio Superette,1858,Lexington Ave,New York,10029,2017,5,40.798118,-73.942006,11.0,8.0,182.0,1052235.0,1.016430e+09,East Harlem North
364,New King Deli Grocery Corp.,23,East 115th St.,New York,10029,2017,5,40.799415,-73.945645,11.0,9.0,184.0,1074184.0,1.016210e+09,East Harlem North
365,Little Mexico Meat Grocery,2119,Third Ave,New York,10029,2017,5,40.797752,-73.940150,11.0,8.0,188.0,1052552.0,1.016650e+09,East Harlem North
366,Paniagua Deli Grocery,203,East 115th St.,New York,10029,2017,5,40.797233,-73.940432,11.0,8.0,188.0,1052555.0,1.016650e+09,East Harlem North
367,JJ Food Market,153,East 99th St.,New York,10029,2017,5,40.787686,-73.949230,11.0,5.0,166.0,1051758.0,1.016270e+09,East Harlem South

In [26]:
# check to see if the names are the same in the two databases
all_store_name_set = set(store_locs['DBA Name'])
healthy_awards = set(data['Store Name'])

healthy_awards&all_store_name_set

{'2001 GOURMET DELI',
 'AMIGOS GROCERY',
 'BANESA DELI GROCERY 2',
 'BODEGA BUILT',
 'C-TOWN',
 'CONCOURSE FOOD PLAZA',
 'FELINO GROCERY',
 'FELOMAR GROCERY STORE',
 'FINE FARE SUPERMARKET',
 'JJN CORP',
 'LOS PRIMOS GROCERY'}